# Generated by Django 2.1.3 on 2018-12-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='penanya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('kategoriPertanyaan', models.CharField(max_length=50)),
                ('babPertanyaan', models.CharField(max_length=50)),
            ],
        ),
    ]
