# Generated by Django 2.1.3 on 2018-12-05 04:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('penanya', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='penanya',
            name='asalSekolah',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='penanya',
            name='minat',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
