# Generated by Django 2.1.3 on 2018-12-05 04:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('penanya', '0002_auto_20181205_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='penanya',
            name='waktubertanya',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
