# Generated by Django 2.1.3 on 2018-12-05 11:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('penanya', '0003_penanya_waktubertanya'),
    ]

    operations = [
        migrations.AddField(
            model_name='penanya',
            name='foto_profil',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
