# Generated by Django 2.1.3 on 2018-12-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penanya', '0004_penanya_foto_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='penanya',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
